from decouple import config

class EnvConfig:
    OPENAI_API_KEY: str = config("OPENAI_API_KEY")
    PROXYCURL_API_KEY = config("PROXYCURL_API_KEY")
    TAVILY_API_KEY = config("TAVILY_API_KEY")
    TWITTER_API_KEY = config("TWITTER_API_KEY")
    TWITTER_API_KEY_SECRET = config("TWITTER_API_KEY_SECRET")
    TWITTER_BEARER_TOKEN = config("TWITTER_BEARER_TOKEN")
    TWITTER_ACCESS_TOKEN = config("TWITTER_ACCESS_TOKEN")
    TWITTER_ACCESS_TOKEN_SECRET = config("TWITTER_ACCESS_TOKEN_SECRET")
    PYTHONPATH = config("PYTHONPATH")
    LANGCHAIN_API_KEY = config("LANGCHAIN_API_KEY")
    LANGCHAIN_TRACING_V2: bool = True if config("LANGCHAIN_TRACING_V2") == "true" else False
    LANGCHAIN_PROJECT = config("LANGCHAIN_PROJECT")
    AZURE_API_VERSION = config("AZURE_API_VERSION")
    AZURE_OPENAI_ENDPOINT = config("AZURE_OPENAI_ENDPOINT")
    AZURE_MODEL_NAME = config("AZURE_MODEL_NAME")
    AZURE_URL_TOKEN = config("AZURE_URL_TOKEN")
    AZURE_CLIENT_ID = config("AZURE_CLIENT_ID")
    AZURE_TENANT_ID = config("AZURE_TENANT_ID")
    AZURE_CLIENT_SECRET = config("AZURE_CLIENT_SECRET")